CREATE TABLE BRAND (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT UN_BRAND UNIQUE(NAME)
);


CREATE TABLE INVENTORY (
    BRAND_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    TIME_RECEIVED TIMESTAMP NOT NULL,
    CONSTRAINT PK_INVENTORY PRIMARY KEY (BRAND_ID, TIME_RECEIVED)
);